#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 17, 2021 05:44:43 PM CEST  platform: Windows NT
#    Jun 17, 2021 06:07:56 PM CEST  platform: Windows NT

import sys
from tkinter import END

import current_configuration
import patient_window
import edit_configuration

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


def init(top, gui, db_connection, *args, **kwargs):
    global w, top_level, root, connection
    w = gui
    top_level = top
    root = top
    connection = db_connection
    refresh_patients()


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def open_current_configuration():
    current_configuration.create_Toplevel1(root)


def refresh_patients():
    global patients_list
    patients_list = connection.get_patients()

    inner_frame = w.Scrolledwindow1_f
    button = {}
    for i in range(len(patients_list)):
        e = tk.Entry(inner_frame, width=70, fg='blue')
        e.grid(row=i, column=1)
        e.insert(END, patients_list[i].PatientID)

        button[i] = tk.Button(inner_frame, text='Open', width=9, command=lambda i=i: open_patient(i))
        button[i].grid(row=i, column=2, sticky='w')
    if button:
        button[0].wait_visibility()
    bbox = inner_frame.bbox()
    w.Scrolledwindow1.configure(scrollregion=bbox)


def open_patient(i):
    print(i)
    patient_window.create_Toplevel1(root, connection, patients_list[i])


def open_edit_configuration():
    edit_configuration.create_Toplevel1(root)

if __name__ == '__main__':
    import dicom_repository

    dicom_repository.vp_start_gui()


