#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 17, 2021 07:54:24 PM CEST  platform: Windows NT

import sys
from tkinter import END

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


def init(top, gui, conn, image1, *args, **kwargs):
    global w, top_level, root, connection, imagefile
    w = gui
    top_level = top
    root = top
    connection = conn
    imagefile = image1
    populate()


def fill_file_fields():
    fields_list = imagefile.file_fields

    inner_frame = w.Scrolledwindow1_f

    entries = {}

    for i in range(len(fields_list)):
        e = tk.Entry(inner_frame, width=20, fg='blue')
        e.grid(row=i, column=1)
        e.insert(END, fields_list[i].keyword)

        e1 = tk.Entry(inner_frame, width=45, fg='blue')
        e1.grid(row=i, column=2)
        e1.insert(END, fields_list[i].value)
        entries[i] = (e, e1)

    entries[0][0].wait_visibility()
    bbox = inner_frame.bbox()
    w.Scrolledwindow1.configure(scrollregion=bbox)


def fill_fields():
    w.Text1.insert(1.0, imagefile.image.image_id)
    w.Text2.insert(1.0, imagefile.image.series_id)
    w.Text3.insert(1.0, imagefile.file.file_id)
    w.Text4.insert(1.0, imagefile.file.file_name)
    w.Text5.insert(1.0, imagefile.file.processed_date)
    w.Text6.insert(1.0, imagefile.image.ImageType)
    w.Text7.insert(1.0, imagefile.image.PixelData)
    w.Scrolledtext1.insert(1.0, imagefile.file.comment if imagefile.file.comment else "")
    w.Text8.insert(1.0, imagefile.file.system_modification_time)
    w.Text9.insert(1.0, imagefile.image.Modality)


def populate():
    fill_fields()
    fill_file_fields()


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def save_comment():
    # print(imagefile.file.file_id)
    # print(w.Scrolledtext1.get("1.0", END))
    connection.save_comment_for_file_id(imagefile.file.file_id, w.Scrolledtext1.get("1.0", END))  # ??????????????????


if __name__ == '__main__':
    import image_window

    image_window.vp_start_gui()
